# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.EC2_SSH_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Debug SSH Command (Optional)
      run: echo "ssh -p $PORT $USER@$HOST"
      env:
        PORT: ${{ secrets.EC2_SSH_PORT }}
        USER: ${{ secrets.EC2_USER }}
        HOST: ${{ secrets.EC2_HOST }}

    - name: Deploy to EC2
      run: |
        ssh -p ${{ secrets.EC2_SSH_PORT }} "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'
        cd /portfolio
        git pull origin main
        docker-compose down
        docker-compose up -d --build
        EOF