# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.EC2_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Debug SSH Key
      run: |
          ls -lah ~/.ssh
          cat ~/.ssh/id_rsa | head -n 5  # Show first few lines to confirm key exists
          ssh-keygen -l -f ~/.ssh/id_rsa || echo "Invalid SSH key"

    - name: Deploy to EC2
      run: |
        ssh -p ${{ secrets.EC2_SSH_PORT }} "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" << 'EOF'
        cd /portfolio
        git pull origin main
        docker-compose down
        docker-compose up -d --build
        EOF