name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: |
          ssh-keyscan -H -p ${{ secrets.EC2_SSH_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_PORT: ${{ secrets.EC2_SSH_PORT }}
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          ENV_VARS: ${{ secrets.ENV_VARS }}
        run: |
          ssh -p $SSH_PORT "$SSH_USER@$SSH_HOST" << EOF
            # Navigate to the project directory
            cd /home/ubuntu/portfolio
            
            # Ensure the repository is clean before pulling
            git reset --hard HEAD
            git clean -fd
            
            # Pull the latest changes from the main branch
            git pull origin main

            # Update environment variables
            echo "$ENV_VARS" > .env
            
            # Rebuild and restart Docker containers
            docker-compose down
            docker-compose up -d --build
            
            # Show the status of running containers
            docker-compose ps
            
            # Clean up dangling Docker images to save space
            docker image prune -af
          EOF