name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.EC2_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_PORT: ${{ secrets.EC2_SSH_PORT }}
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -p $SSH_PORT "$SSH_USER@$SSH_HOST" << 'EOF'
            cd /portfolio
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF