name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts
        run: |
          ssh-keyscan -H -p ${{ secrets.EC2_SSH_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_PORT: ${{ secrets.EC2_SSH_PORT }}
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -p $SSH_PORT "$SSH_USER@$SSH_HOST" << 'EOF'
            cd /home/ubuntu/portfolio
            
            # Stash any local changes
            git stash
            
            # Pull latest changes
            git pull origin main
            
            # Rebuild and restart containers
            docker-compose down
            docker-compose up -d --build
            
            # Show container status
            docker-compose ps
            
            # Clean up old images
            docker image prune -f
          EOF